// All educational content for the landing page
export const CPU_COMPONENTS = [
  {
    id: 'cu',
    name: 'Control Unit',
    abbr: 'CU',
    color: 'amber',
    icon: '🧭',
    tagline: 'The Director',
    simple: 'Tells every part of the CPU what to do and when.',
    detail: 'The Control Unit reads each instruction and breaks it into micro-signals — "read memory now", "send data to ALU", "store result". It never does math itself; it just orchestrates the other parts.',
    analogy: 'Think of it as an orchestra conductor: it doesn\'t play any instrument, but every musician follows its cue.',
    facts: ['Decodes opcodes from the CIR', 'Generates control signals across the Control Bus', 'Sequences the Fetch → Decode → Execute cycle'],
  },
  {
    id: 'alu',
    name: 'Arithmetic Logic Unit',
    abbr: 'ALU',
    color: 'rose',
    icon: '⚡',
    tagline: 'The Calculator',
    simple: 'Does all the actual math and logic comparisons.',
    detail: 'The ALU performs addition, subtraction, multiplication, division, and bitwise logic (AND, OR, NOT). It takes two inputs (usually from the Accumulator and MBR), applies the operation, and outputs the result back to the Accumulator.',
    analogy: 'Like a pocket calculator embedded directly inside the processor — blindingly fast.',
    facts: ['Handles: ADD, SUB, MUL, DIV, AND, OR, NOT, CMP', 'Updates status flags: Zero, Negative, Carry, Overflow', 'Result goes directly to the Accumulator'],
  },
];

export const REGISTERS = [
  {
    id: 'pc',
    name: 'Program Counter',
    abbr: 'PC',
    color: 'emerald',
    icon: '📍',
    tagline: 'The Bookmark',
    simple: 'Remembers which instruction to fetch next.',
    detail: 'At the start of every Fetch cycle, the PC\'s value is copied to the MAR so the right memory address is read. Then it auto-increments to point to the next instruction. A jump instruction can overwrite it to create loops or branches.',
    width: '8-bit (0–255)',
  },
  {
    id: 'mar',
    name: 'Memory Address Register',
    abbr: 'MAR',
    color: 'cyan',
    icon: '📮',
    tagline: 'The Postcode',
    simple: 'Holds the address of the memory location being accessed.',
    detail: 'Before any memory read or write can happen, the target address must be placed here. The MAR then asserts that address onto the Address Bus so the memory controller can find the right cell.',
    width: '8-bit (addresses 0–255)',
  },
  {
    id: 'mbr',
    name: 'Memory Buffer Register',
    abbr: 'MBR',
    color: 'violet',
    icon: '📦',
    tagline: 'The Loading Dock',
    simple: 'Temporarily holds data coming from or going to memory.',
    detail: 'On a READ: data comes from RAM via the Data Bus and lands here before moving to the ALU or CIR. On a WRITE: data from the Accumulator is placed here before being pushed to RAM. It acts as a buffer to decouple the CPU\'s speed from memory\'s slower speed.',
    width: '8-bit data word',
  },
  {
    id: 'cir',
    name: 'Current Instruction Register',
    abbr: 'CIR',
    color: 'blue',
    icon: '📋',
    tagline: 'The Active Ticket',
    simple: 'Holds the instruction that is currently being executed.',
    detail: 'Once an instruction is fetched from RAM into the MBR, it\'s moved here. The Control Unit then splits it: the opcode tells it what to do (ADD, LOAD…), and the operand provides the data address or value needed.',
    width: 'Opcode + Operand fields',
  },
  {
    id: 'acc',
    name: 'Accumulator',
    abbr: 'ACC',
    color: 'orange',
    icon: '🏦',
    tagline: 'The Running Total',
    simple: 'Holds the result of every calculation.',
    detail: 'Every arithmetic or logical operation ends here. If you ADD two numbers, the result goes into the ACC. If you LOAD a value from memory, it goes into the ACC. It\'s the primary working register of the ALU.',
    width: '8-bit (0–255)',
  },
  {
    id: 'gpr',
    name: 'General Purpose Registers',
    abbr: 'R0–R3',
    color: 'teal',
    icon: '🗄️',
    tagline: 'Fast Scratch Pads',
    simple: 'Extra fast storage inside the CPU for temporary values.',
    detail: 'Unlike RAM (which is slow to access), registers are inside the CPU and take zero extra clock cycles. Programs store frequently used variables here to avoid slow memory trips.',
    width: '4 registers, 8-bit each',
  },
];

export const BUSES = [
  {
    id: 'address',
    name: 'Address Bus',
    color: 'cyan',
    direction: 'CPU → Memory (one-way)',
    icon: '→',
    simple: 'Carries the "where" — the memory address the CPU wants to read or write.',
    detail: 'It is strictly one-way: only the CPU (via the MAR) can put addresses on it. Memory and I/O devices only listen. The width of this bus limits how much memory the system can address (8-bit = 256 cells).',
    analogy: '"I want house number 42, please."',
  },
  {
    id: 'data',
    name: 'Data Bus',
    color: 'violet',
    direction: 'CPU ↔ Memory (two-way)',
    icon: '↔',
    simple: 'Carries the actual data or instruction being moved.',
    detail: 'This bus goes both directions. During a READ, data travels from RAM to the MBR. During a WRITE, data goes from the MBR to RAM. Its width defines the machine\'s word size (how many bits move per cycle).',
    analogy: '"Here is the package for house 42." or "Send me the package from house 42."',
  },
  {
    id: 'control',
    name: 'Control Bus',
    color: 'amber',
    direction: 'CPU ↔ Memory + Components',
    icon: '⚡',
    simple: 'Carries command signals — READ, WRITE, CLOCK, INTERRUPT.',
    detail: 'This is the nervous system. While the Address Bus says "where" and the Data Bus says "what", the Control Bus says "how" and "when". Signals like Memory Read, Memory Write, and Clock synchronize every component so they act at exactly the right moment.',
    analogy: '"Action!" / "Cut!" — it\'s the director\'s commands, not the content.',
  },
];
